dist: trusty
sudo: false
language: python

# Python 3.7+ needs a newer version of openssl than is available in trusty,
# so these must run on a newer platform (and since travis doesn't yet have
# containers for xenial, those must use VMs).
# YAML magic from https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-401924248
.mixins:
- &xenial-mixin
  dist: xenial
  sudo: true
  addons:
    apt:
      packages:
        - libgnutls-dev

stages:
    - linting
    - test
cache: pip
script: tox --recreate
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy
install: travis_retry pip install tox-travis
services:
  - mongodb
  - redis-server
before_script:
  - sleep 15
  - mongo eve_test --eval 'db.createUser({user:"test_user",pwd:"test_pw",roles:["readWrite"]});'

jobs:
    include:
    - stage: linting
      python: '3.6'
      env:
      install:
      - pip install pre-commit
      - pre-commit install-hooks
      before_script:
      services:
      script:
      - pre-commit run --all-files
    - stage: test
      <<: *xenial-mixin
      python: '3.7'
